{% set name = "voici-packages" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/v/voici_core/voici_core-{{ version }}.tar.gz
    sha256: 922299ef90e900fec6339e4ad0086ac4428c86e1d30c8265275e990bd37b8b83
    folder: voici_core
  - url: https://pypi.org/packages/source/v/voici/voici-{{ version }}.tar.gz
    sha256: 303cda2d5e9a2d775330ae4de6abb79c2061e3d3181493fbd6901984d3d109fb
    folder: voici

build:
  noarch: python
  number: 0

outputs:
  - name: voici_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd voici_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - voici = voici_core.app:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - nodejs >=18,<19
        - hatch-jupyter-builder >=0.5.3
        - hatchling >=1.8.1
      run:
        - python >={{ python_min }}
        - voila >=0.5.5,<0.6
        - jupyterlite-core >=0.2.0,<0.6.0
    test:
      requires:
        - python {{ python_min }}
      imports:
        - voici_core
      commands:
        - voici --help

  - name: voici
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd voici
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - hatch-jupyter-builder >=0.5.3
        - hatchling >=1.8.1
      run:
        - python >={{ python_min }}
        - voici_core
        - jupyterlite-xeus >=2.0.0,<4
      run_constrained:
        - voici_core ={{ version }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - voici
        - jupyterlite_xeus
      commands:
        - voici --help

about:
  home: https://github.com/voila-dashboards/voici
  license: BSD-3-Clause
  license_family: BSD
  license_file: voici/LICENSE
  summary: Voici turns Jupyter notebooks into static web applications
  description: |
    Voici is a tool for generating static dashboards from Jupyter Notebooks.
    It can be used as a drop-in replacement for Voilà and it has the same
    commands and supports most of Voilà's configuration options.

    Unlike Voilà, which renders interactive dashboards using server-side execution,
    Voici uses WebAssembly (Wasm) kernels to render notebooks in the browser,
    making the resulting dashboard entirely self-contained and distributable.
  dev_url: https://github.com/voila-dashboards/voici

extra:
  recipe-maintainers:
    - jtpio
    - trungleduc
    - martinRenou
