{% set name = "voici" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ffb956c0e651759859850865048d075134e7266b0d1ef4d09c3b49a38b886bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voici = voici.app:main

requirements:
  host:
    - python >=3.8
    - pip
    - nodejs >=18,<19
    - hatch-jupyter-builder >=0.5.3
    - hatchling >=1.8.1
  run:
    - python >=3.8
    - voila >=0.5.5,<0.6
    - jupyterlite-core >=0.2.0,<0.3.0

test:
  imports:
    - voici
  commands:
    - voici --help

about:
  home: https://github.com/voila-dashboards/voici
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Voici turns Jupyter notebooks into static web applications
  description: |
    Voici is a tool for generating static dashboards from Jupyter Notebooks.
    It can be used as a drop-in replacement for Voilà and it has the same
    commands and supports most of Voilà's configuration options.

    Unlike Voilà, which renders interactive dashboards using server-side execution,
    Voici uses WebAssembly (Wasm) kernels to render notebooks in the browser,
    making the resulting dashboard entirely self-contained and distributable.
  dev_url: https://github.com/voila-dashboards/voici

extra:
  recipe-maintainers:
    - jtpio
    - trungleduc
    - martinRenou
